/**
 * GENERATED by `bun scripts/gen-bundled.ts` (also runs as part of `bun run build-catalog`) —
 * never edit by hand. datasetId -> schemaHash for every dataset baked into public/data/.
 *
 * OWNER: platform. In demo mode (DEMO_MODE=true) the Worker only answers /api/plan and
 * /api/chart for a datasetId listed here whose schemaHash matches exactly; anything else
 * (an upload, or a bundled dataset rebuilt without regenerating this file) gets
 * 403 { error: "demo_restricted" }.
 */
export const BUNDLED_DATASETS: Record<string, string> = {
  "afl": "573a16ad9999b2a4",
  "nobel": "ea2c949575f65791",
  "swift": "c4a4ce859d6bb89a",
  "world": "e25776a0deca97f9",
}
