/**
 * OWNER: platform. Generates shared/bundled.ts: the map of bundled dataset id -> schemaHash that
 * the public demo uses to restrict /api/plan and /api/chart to the datasets it ships with (no
 * uploads in demo mode). Reads every public/data/<id>.catalog.json written by
 * `bun scripts/build-catalog.ts` and re-runs whenever that script does — wired into
 * `bun run build-catalog` in package.json.
 *
 * Usage: `bun scripts/gen-bundled.ts`
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"

interface CatalogLike {
  datasetId: string
  schemaHash: string
}

const root = path.resolve(import.meta.dirname, "..")
const dataDir = path.join(root, "public", "data")
const outFile = path.join(root, "shared", "bundled.ts")

function readCatalogs(): CatalogLike[] {
  const files = readdirSync(dataDir).filter((f) => f.endsWith(".catalog.json"))
  const catalogs = files.map((f) => {
    const raw = JSON.parse(readFileSync(path.join(dataDir, f), "utf-8")) as Partial<CatalogLike>
    if (!raw.datasetId || !raw.schemaHash) {
      throw new Error(`${f}: missing datasetId or schemaHash — was it built by scripts/build-catalog.ts?`)
    }
    return { datasetId: raw.datasetId, schemaHash: raw.schemaHash }
  })
  return catalogs.sort((a, b) => a.datasetId.localeCompare(b.datasetId))
}

function render(catalogs: CatalogLike[]): string {
  const entries = catalogs.map((c) => `  ${JSON.stringify(c.datasetId)}: ${JSON.stringify(c.schemaHash)},`).join("\n")
  return `/**
 * GENERATED by \`bun scripts/gen-bundled.ts\` (also runs as part of \`bun run build-catalog\`) —
 * never edit by hand. datasetId -> schemaHash for every dataset baked into public/data/.
 *
 * OWNER: platform. In demo mode (DEMO_MODE=true) the Worker only answers /api/plan and
 * /api/chart for a datasetId listed here whose schemaHash matches exactly; anything else
 * (an upload, or a bundled dataset rebuilt without regenerating this file) gets
 * 403 { error: "demo_restricted" }.
 */
export const BUNDLED_DATASETS: Record<string, string> = {
${entries}
}
`
}

const catalogs = readCatalogs()
if (catalogs.length === 0) throw new Error(`No *.catalog.json found in ${dataDir} — run \`bun scripts/build-catalog.ts\` first.`)
writeFileSync(outFile, render(catalogs))
console.log(`shared/bundled.ts: ${catalogs.map((c) => c.datasetId).join(", ")}`)
